#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

xset r rate 235 65
#setxkbmap us -variant colemak_dh_ortho -option caps:swapescape
/usr/bin/xscreensaver --no-splash &
light-locker &
~/.config/polybar/scripts/loadicons
~/.config/polybar/scripts/launch
rotate_img_colors -- ~/Pictures/bgs/med.png
sed -Ein -f ~/.config/bspwm/histclean.sed ~/.bash_history
#~/.fehbg
picom &

bspc monitor -d a b c d e f g h i 

bspc config border_width         0
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Zathura state=tiled
#bspc rule -a firefox state=floating rectangle=1366x742+0+25


#bspc rule -a C-evo-dh-gtk2 state=fullscreen
bspc rule -a C-evo-dh-gtk2 state=floating

