#!/usr/bin/env bash

if systemctl is-active --quiet bluetooth.service; then
	sudo systemctl stop bluetooth.service
	while systemctl is-active --quiet bluetooth.service; do
	    sleep 1
	done
	icon="" 

	# You can now add your additional commands here.
	# For example:
	# bluetoothctl power on
	# bluetoothctl connect AA:BB:CC:DD:EE:FF
else
	sudo systemctl start bluetooth.service
	while ! systemctl is-active --quiet bluetooth.service; do
	    sleep 1
	done
	icon="" 

	# You can now add your additional commands here.
	# For example:
	# bluetoothctl power on
	# bluetoothctl connect AA:BB:CC:DD:EE:FF
fi

echo ${icon} > /dev/shm/bluetooth/icon
echo "%{F$(cat /dev/shm/bluetooth/color)}%{T1}bt %{T3}${icon}" 

